import type { CloudFailureClass } from '@/data/meetings';

export type CloudFailureOperation = 'create_job' | 'poll_job' | 'retry_provider' | 'sync_source';

const TRANSPORT_FAILURES = new Set<CloudFailureClass>([
  'offline', 'dns', 'tls', 'socket', 'timeout', 'transport_unknown',
]);

const codeOf = (cause: unknown): string => {
  if (!cause || typeof cause !== 'object') return '';
  const direct = (cause as { code?: unknown }).code;
  const nested = (cause as { cause?: { code?: unknown } }).cause?.code;
  return String(typeof direct === 'string' ? direct : typeof nested === 'string' ? nested : '').toUpperCase();
};

const typedFailureClassOf = (cause: unknown): CloudFailureClass | null => {
  if (!cause || typeof cause !== 'object') return null;
  const value = (cause as { failureClass?: unknown }).failureClass;
  return typeof value === 'string' && value in SAFE_COPY
    ? value as CloudFailureClass
    : null;
};

/** Classify only typed fields. Human-readable messages are never parsed. */
export function classifyTransportCause(cause: unknown): CloudFailureClass {
  const typed = typedFailureClassOf(cause);
  if (typed) return typed;
  const name = cause instanceof Error ? cause.name.toUpperCase() : '';
  const code = codeOf(cause);
  if (name === 'ABORTERROR' || ['ABORT_ERR', 'ETIMEDOUT', 'TIMEOUT'].includes(code)) return 'timeout';
  if (['OFFLINE', 'NETWORK_OFFLINE', 'ENETDOWN', 'ENETUNREACH'].includes(code)) return 'offline';
  if (['ENOTFOUND', 'EAI_AGAIN', 'UNKNOWN_HOST', 'ERR_DNS'].includes(code)) return 'dns';
  if (['CERT_INVALID', 'CERT_HAS_EXPIRED', 'ERR_TLS', 'ERR_SSL', 'SSL_ERROR'].includes(code)) return 'tls';
  if (['ECONNRESET', 'ECONNREFUSED', 'ECONNABORTED', 'EPIPE', 'SOCKET_CLOSED'].includes(code)) return 'socket';
  return 'transport_unknown';
}

export function classifyHttpFailure(status: number, code?: string | null): CloudFailureClass {
  const machineCode = code?.trim().toLowerCase() ?? '';
  if (status === 401 || status === 403) return 'auth';
  if (['failed_retryable', 'budget_guardrail_blocked', 'provider_busy'].includes(machineCode)) {
    return 'backend_retryable';
  }
  if (['failed_terminal', 'validation_failed', 'source_conflict', 'protocol_error'].includes(machineCode)) {
    return 'backend_terminal';
  }
  if (status === 408 || status === 425 || status === 429 || status >= 500) return 'http_retryable';
  if (status >= 400) return 'http_terminal';
  return 'protocol';
}

export function isTransportFailure(value: CloudFailureClass | null | undefined): boolean {
  return !!value && TRANSPORT_FAILURES.has(value);
}

const SAFE_COPY: Record<CloudFailureClass, string> = {
  offline: 'Waiting for internet. Maina will continue automatically.',
  dns: 'Waiting for internet. Maina will continue automatically.',
  tls: 'Waiting for internet. Maina will continue automatically.',
  socket: 'Waiting for internet. Maina will continue automatically.',
  timeout: 'Waiting for internet. Maina will continue automatically.',
  transport_unknown: 'Waiting for internet. Maina will continue automatically.',
  auth: 'Reconnect Maina Cloud. Your recording and transcript are safe.',
  http_retryable: 'Maina Cloud is temporarily busy. Maina will retry automatically.',
  backend_retryable: 'Maina Cloud is temporarily busy. Maina will retry automatically.',
  http_terminal: 'Cloud notes need attention. Your recording and transcript are safe.',
  backend_terminal: 'Cloud notes need attention. Your recording and transcript are safe.',
  protocol: 'Cloud notes need attention. Your recording and transcript are safe.',
};

const SAFE_VALUES = new Set(Object.values(SAFE_COPY));

export function safeCloudFailureMessage(value: CloudFailureClass): string {
  return SAFE_COPY[value];
}

/** Permit only copy generated by this closed mapping; raw server text is dropped. */
export function safePersistedCloudMessage(
  message: string | null | undefined,
  fallback: string,
): string {
  const value = message?.trim() ?? '';
  if (SAFE_VALUES.has(value)) return value;
  return SAFE_VALUES.has(fallback)
    ? fallback
    : SAFE_COPY.transport_unknown;
}
