Pod::Spec.new do |s|
  s.name           = 'MainaRecorder'
  s.version        = '0.1.0'
  s.summary        = 'Maina iOS recorder bridge'
  s.description    = 'Native iOS recording, route, and durable processing bridge for Maina.'
  s.author         = 'Maina'
  s.homepage       = 'https://github.com/divayhere/maina'
  s.platforms      = {
    :ios => '16.4',
    :tvos => '16.4'
  }
  s.source         = { git: '' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'
  # Generated by scripts/prepare-ios-sherpa-runtime.sh. This stays out of Git
  # and is checksum-pinned so a clean machine cannot silently link an unknown
  # ASR runtime. Capture remains buildable while the optional runtime is being
  # installed; the native module explicitly reports ASR unavailable until then.
  sherpa_framework = 'vendor/sherpa-onnx.xcframework'
  s.vendored_frameworks = sherpa_framework if File.exist?(File.join(__dir__, sherpa_framework))
  s.frameworks = 'Accelerate', 'AVFAudio'

  # Swift/Objective-C compatibility
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
  }

  s.source_files = "**/*.{h,m,mm,swift,hpp,cpp}"
end
