Pod::Spec.new do |s|
  s.name           = 'MainaRecorder'
  s.version        = '0.1.0'
  s.summary        = 'Maina iOS recorder bridge'
  s.description    = 'Native iOS recording, route, and durable processing bridge for Maina.'
  s.author         = 'Maina'
  s.homepage       = 'https://github.com/divayhere/maina'
  s.platforms      = {
    :ios => '16.4',
    :tvos => '16.4'
  }
  s.source         = { git: '' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'
  # Keep this exactly aligned with Sherpa v1.13.4's official iOS build input.
  # Sherpa's no-TTS XCFramework contains ASR code but intentionally leaves the
  # ONNX Runtime symbols for the host application to provide.
  s.dependency 'onnxruntime-objc', '1.27.0'
  # Generated by scripts/prepare-ios-sherpa-runtime.sh. This stays out of Git
  # and is checksum-pinned so a clean machine cannot silently link an unknown
  # ASR runtime. It is mandatory: a release must not claim local transcription
  # while quietly shipping a capture-only binary.
  sherpa_framework = 'vendor/sherpa-onnx.xcframework'
  raise 'Run npm run ios:runtime before pod install.' unless File.exist?(File.join(__dir__, sherpa_framework))
  s.vendored_frameworks = sherpa_framework
  s.frameworks = 'Accelerate', 'AVFAudio'

  # Swift/Objective-C compatibility
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
  }

  s.source_files = "*.{h,m,mm,swift,hpp,cpp}"
end
