plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.divay.maina'
version = '0.1.0'

android {
  namespace 'com.divay.maina.recorder'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'androidx.work:work-runtime-ktx:2.10.5'
}
