import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, ScrollView, View } from 'react-native';

import { deleteMeeting, getMeeting, type Meeting } from '@/data/meetings';
import { AppText, Card } from '@/design/components';
import { useAppTheme } from '@/design/theme';
import { radius, space } from '@/design/tokens';
import { useMeetings } from '@/state/meetingsStore';
import { formatDateTime, formatDuration } from '@/utils/format';

export default function MeetingDetail() {
  const { theme } = useAppTheme();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { refresh } = useMeetings();
  const [meeting, setMeeting] = useState<Meeting | null>(null);

  useFocusEffect(
    useCallback(() => {
      if (id) getMeeting(id).then(setMeeting);
    }, [id]),
  );

  const confirmDelete = () => {
    Alert.alert('Delete meeting?', 'This removes the meeting and its recording.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          if (!id) return;
          await deleteMeeting(id);
          await refresh();
          router.back();
        },
      },
    ]);
  };

  return (
    <View style={{ flex: 1, backgroundColor: theme.bg }}>
      <View style={styles.topbar}>
        <Pressable onPress={() => router.back()} hitSlop={12}>
          <Ionicons name="chevron-back" size={26} color={theme.text} />
        </Pressable>
        <Pressable onPress={confirmDelete} hitSlop={12}>
          <Ionicons name="trash-outline" size={22} color={theme.rec} />
        </Pressable>
      </View>

      <ScrollView contentContainerStyle={{ padding: space.lg, gap: space.lg }}>
        <View style={{ gap: space.xs }}>
          <AppText variant="title">{meeting?.title ?? 'Meeting'}</AppText>
          {meeting ? (
            <AppText variant="body" muted>
              {formatDateTime(meeting.startedAt)} · {formatDuration(meeting.durationMs)}
            </AppText>
          ) : null}
        </View>

        <Card style={{ gap: space.sm }}>
          <AppText variant="label" muted>TRANSCRIPT</AppText>
          <AppText variant="body" muted>
            {meeting?.transcript
              ? meeting.transcript
              : 'On-device transcription arrives in Phase 2. Your recording is saved and ready.'}
          </AppText>
        </Card>

        <Card style={{ gap: space.sm }}>
          <AppText variant="label" muted>SUMMARY & TO-DOS</AppText>
          <AppText variant="body" muted>
            {meeting?.summary
              ? meeting.summary
              : 'Summaries and to-dos arrive in Phase 3, generated by your chosen AI.'}
          </AppText>
        </Card>

        <View style={[styles.audioTag, { borderColor: theme.border }]}>
          <Ionicons
            name={meeting?.audioUri ? 'musical-note' : 'alert-circle-outline'}
            size={16}
            color={meeting?.audioUri ? theme.done : theme.warn}
          />
          <AppText variant="label" muted>
            {meeting?.audioUri ? 'Audio captured' : 'No audio file'}
          </AppText>
        </View>
      </ScrollView>
    </View>
  );
}

import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
  topbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: space.lg,
    paddingTop: space.xxxl,
    paddingBottom: space.sm,
  },
  audioTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: radius.pill,
    paddingHorizontal: space.md,
    paddingVertical: 6,
  },
});
